using Microsoft.AspNetCore.Identity;

namespace WarehouseManager.Core;

// Add profile data for application users by adding properties to the ApplicationUser class
// TODO autogenerated by Identity change and add more profile info about the users
public class ApplicationUser : IdentityUser
{
}